---
permalink: san-host/task_preparing_to_transition_hp_ux_host_luns_with_file_systems.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, hp, ux, host, lun, file, system 
summary: 将具有文件系统的 HP-UX 主机 LUN 从 7- 模式 Data ONTAP 过渡到集群模式 Data ONTAP 之前，必须收集过渡过程所需的信息。 
---
= 准备过渡具有文件系统的 HP-UX 主机 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将具有文件系统的 HP-UX 主机 LUN 从 7- 模式 Data ONTAP 过渡到集群模式 Data ONTAP 之前，必须收集过渡过程所需的信息。

.步骤
. 显示 LUN 以确定要过渡的 LUN 的名称：
+
` * LUN 显示 *`

. 找到要过渡的 LUN 的 SCSI 设备名称以及 SCSI 设备的 Agile 名称：
+
` * sanlun lun show -p*`

+
在以下示例中，过渡 LUN 为 lun1 和 lun3 。lun1 的 SCSI 设备名称是 ` /dev/dsk/c14t0d1` ， ` /dev/dsk/c27t0d1` ， ` /dev/dsk/c40t0d1` 和 ` /dev/dsk/c31t0d1` 。`LUN3` 的 SCSI 设备名称是 ` /dev/dsk/c14t0d2` ， ` /dev/dsk/c27t0d2` ， ` /dev/dsk/c40t0d2` 和 ` /dev/dsk/c31t0d2` 。

+
SCSI 设备 ` /dev/dsk/c31t0d1` 的敏捷名称是 ` /dev/rdisk/disk11` 。

+
[listing]
----
        ONTAP Path: f8040-211-185:/vol/vol185_n1/lun3
               LUN: 1
          LUN Size: 3g
       Host Device: /dev/rdisk/disk11
              Mode: 7
Multipath Provider: None
host      vserver   /dev/dsk
path      path      filename           host     vserver
state     type      or hardware path   adapter  LIF
-----     --------- ----------------   -------  -------
up        secondary /dev/dsk/c14t0d1   fcd0     fc4
up        primary   /dev/dsk/c27t0d1   fcd0     fc2
up        primary   /dev/dsk/c40t0d1   fcd1     fc1
up        secondary /dev/dsk/c31t0d1   fcd1     fc3
----
+
[listing]
----
        ONTAP Path: f8040-211-183:/vol/vol183_n1/lun1
               LUN: 3
          LUN Size: 3g
       Host Device: /dev/rdisk/disk14
              Mode: 7
Multipath Provider: None
host      vserver   /dev/dsk
path      path	     filename           host     vserver
state     type      or hardware path   adapter  LIF
-----     --------- ----------------   -------  -------
up        secondary /dev/dsk/c14t0d1   fcd0     fc4
up        primary   /dev/dsk/c27t0d1   fcd0     fc2
up        primary   /dev/dsk/c40t0d1   fcd1     fc1
up        secondary /dev/dsk/c31t0d1   fcd1     fc3
----
. 确定主机上 LUN 的 WWID ：
+
` * scsimgr get_info -D _Agle_name_for_SCSI_device_*`

+
在此示例中，设备 ` /dev/rdisk/disk11` 的 LUN WWID 为 0x600a09804d537739422445386b755529 ：

+
[listing]
----
bash-2.05# scsimgr get_info -D /dev/rdisk/disk11 |grep WWID
World  Wide Identifier (WWID)     = 0x600a09804d537739422445386b755529
----
. 列出并记录卷组：
+
` * vgdisplay*`

. 列出并记录卷组，逻辑卷和物理卷：
+
` * vgdisplay -v _vg_name_*`

. 将卷组的 VGID 和逻辑卷写入映射文件：
+
` * vgexport -p -s -m /tmp/mapfile/vg01 vg01*`

. 将 `mapfile.vg01` 的备份副本备份到外部源。
. 列出并记录挂载点：
+
` * bdf*`

+
以下示例显示了挂载点的显示方式：

+
[listing]
----
bash-2.05# bdf
Filesystem     kbytes      used        avail   	used   Mounted on
/dev/vg01/lvol 123592960   1050952   22189796   5%   /mnt/qa/vg01
/dev/vg01/lvol2 23592960   588480    22645044   3%   /mnt/qa/vg02
----

