---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_zfs_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, data, lun, zfs 
summary: 在将具有 ZFS 文件系统的 Solaris 主机 LUN 从 7- 模式 Data ONTAP 过渡到集群模式 Data ONTAP 之前，您必须收集过渡过程所需的信息。 
---
= 准备过渡具有 ZFS 文件的 Solaris 主机数据 LUN 系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在将具有 ZFS 文件系统的 Solaris 主机 LUN 从 7- 模式 Data ONTAP 过渡到集群模式 Data ONTAP 之前，您必须收集过渡过程所需的信息。

这种基于适用场景副本的过渡和无副本过渡。

.步骤
. 在 7- 模式控制器上，确定要过渡的 LUN 的名称：
+
` * LUN 显示 *`

+
[listing]
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----
. 在主机上，找到 LUN 的 SCSI 设备文件名：
+
` * sanlun lun show*`

+
SCSI 设备文件名位于 `device filename` 列中。

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g      7
----
. 列出 zpool ：
+
` * zpool list*`

. 记录 zpool 并获取与 zpool 关联的磁盘：
+
` * zpool status _pool-name_*`

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -

# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
. 列出并记录 ZFS 存储池中的 ZFS 数据集：
+
` * zfs list*`

+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2
----

