---
permalink: san-host/task_testing_luns_with_file_systems_on_lvm_devices_before_cutover_phase.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, file, system, lvm, devices, cutover, phase 
summary: 如果使用 7- 模式过渡工具 \ （ 7MTT\ ） 2.2 或更高版本以及 Data ONTAP 8.3.2 或更高版本对 Red Hat Enterprise Linux \ （ RHEL\ ）主机执行基于副本的过渡，则可以在转换阶段之前测试 LVM 设备上具有文件系统的已过渡集群模式 Data ONTAP LUN 。在测试期间，源主机可以继续对源 7- 模式 LUN 运行 I/O 。 
---
= 在之前测试 LVM 设备上具有文件系统的 LUN 基于副本的过渡的转换阶段
:icons: font
:imagesdir: ../media/


[role="lead"]
如果使用 7- 模式过渡工具（ 7MTT ） 2.2 或更高版本以及 Data ONTAP 8.3.2 或更高版本对 Red Hat Enterprise Linux （ RHEL ）主机执行基于副本的过渡，则可以在转换阶段之前测试 LVM 设备上具有文件系统的已过渡集群模式 Data ONTAP LUN 。在测试期间，源主机可以继续对源 7- 模式 LUN 运行 I/O 。

* 新的集群模式 Data ONTAP LUN 必须映射到测试主机。
* LUN 必须已做好过渡准备。


您应保持测试主机与源主机之间的硬件奇偶校验，并应在测试主机上执行以下步骤。

测试期间，集群模式 Data ONTAP LUN 处于读 / 写模式。测试完成后，它们将转换为只读模式，而您正在为转换阶段做准备。

在测试模式下，您不能停用或导出卷组。因此，在测试主机上挂载逻辑卷时，可能会看到文件系统错误。

.步骤
. 基线数据复制完成后，在 7MTT 用户界面（ UI ）中选择 * 测试模式 * 。
. 在 7MTT UI 中，单击 * 应用配置 * 。
. 在测试主机上，发现新的集群模式 Data ONTAP LUN ：
+
` * 重新扫描 -scsi-bus.sh*`

. 验证是否已发现新的集群模式 Data ONTAP LUN ：
+
` * sanlun lun show*`

. 为集群模式 Data ONTAP LUN 配置 DMMP 设备：
+
` * 多路径 *`

. 获取集群模式 Data ONTAP LUN 的设备句柄 ID ：
+
` * 多路径 -ll*`

+
以下是设备句柄 ID 的示例： "`3600a09804d532d79565d47617679764d` "

. 确定 LVM 使用的 DMMP 设备：
+
` * pvscy*`

+
3600a09804d532d79565d476176797655 是 LVM 使用的 DMMP 设备示例。

. 确定卷组：
+
` * vgscy*`

. 确定逻辑卷：
+
` * lvscann*`

. 启用逻辑卷： * ` * vgchange -ay _volume_group_*`
. 验证逻辑卷状态： * ` * lvdisplay*`
+
输出中的 `LV Status` 列应显示 Available 。

. 确定源主机上的 ` /etc/fstab` 文件中是否存在逻辑卷的挂载点条目。
+
在以下示例中，逻辑卷 ` /dev/mapper/vg_7MTT-lv1` 显示在 ` /etc/fstab` 文件中：

+
[listing]
----
# /etc/fstab
...
tmpfs   /dev/shm  tmpfs   defaults        0 0
devpts  /dev/pts  devpts  gid=5, mode=620 0 0
sysfs   /sys      sysfs   defaults        0 0
proc    /proc     proc    defaults        0 0
/dev/mapper/vg_7MTT-lv1 /7MTT  ext4  defaults 0	0
----
. 如果源主机上的 ` /etc/fstab` 文件中存在逻辑卷的挂载点条目，请手动编辑测试主机上的 ` /etc/fstab` 文件以添加挂载点条目。
. 挂载挂载点：
+
` * 挂载 -A*`

. 验证挂载点是否已挂载：
+
` * 挂载 *`

. 根据需要执行测试。
. 完成测试后，关闭主机：
+
` * shutdown -h -t0 now*`

. 在 7MTT UI 中，单击 * 完成测试 * 。


如果要将集群模式 Data ONTAP LUN 重新映射到源主机，则必须为源主机做好转换阶段的准备。如果集群模式 Data ONTAP LUN 仍要映射到测试主机，则无需在测试主机上执行其他步骤。

* 相关信息 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[从清单评估工作簿收集过渡前信息]

xref:task_preparing_for_cutover_when_transitioning_linux_host_file_systems_on_lvm_devices.adoc[过渡 Linux 主机文件系统时为转换阶段做准备 在 LVM 设备上]
