---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: 如果在 7- 模式 Data ONTAP 中不支持比较和写入 \ （ CAW\ ），则在过渡到集群模式 Data ONTAP 时必须手动启用 CAW 支持。默认情况下，集群模式 Data ONTAP 支持 CAW 。 
---
= 使用 ESXi 命令行界面在数据存储库上启用 CAW
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在 7- 模式 Data ONTAP 中不支持比较和写入（ CAW ），则必须在过渡到集群模式 Data ONTAP 时手动启用 CAW 支持。默认情况下，集群模式 Data ONTAP 支持 CAW 。

* VMFS 数据存储库上不能存在正在运行的 I/O 或 VM 。
* 如果数据存储库已迁移，则必须重新挂载它。
* 您必须具有 7- 模式过渡工具（ 7MTT ）映射文件中的新 ONTAP LUN naa ID 。


只有当 VMFS 数据存储库上没有正在运行的活动 I/O 或 VM 时，才必须启用 CAW 。

* 只有当 VMFS 数据存储库上没有正在运行的活动 I/O 或 VM 时，才必须启用 CAW 。
* 对于基于副本的过渡，请在 7MTT 中完成存储转换操作后执行以下步骤。
* 对于无副本过渡，请在 7MTT 中的导入数据和配置操作完成后执行以下步骤。


.步骤
. 打开清单收集工具（ ICT ）生成的清单评估工作簿。
. 导航到 SAN 主机文件系统选项卡。
. 验证数据存储库的 CAW 状态。
+
数据存储库的 * ATS/CAW* 值应显示 * 已禁用 * ，文件系统列应显示 * VMFS.x* 。

. 记下磁盘列中的数据存储库名称
. 使用 SSH 登录到 ESXi 控制台。
. 列出设备和分区详细信息：
+
` *~ # vmkfstools -ph -v1 _datastore_path_*`

+
datastore_path 是清单评估工作簿 _ 的磁盘列中的数据存储库名称。

+
` * # vmkfstools -Ph -v1 /vmfs/volumes/datastorename*`

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. 记下第一个设备名称和分区编号。
+
在上面的示例中， `naa.600a098044314c6c442b446d51376749 ： 1` 是设备名称和分区编号。

. 使用设备 ID 和分区编号在数据存储库上启用 CAW ：
+
` *~ # vmkfstools -configATSOnly 1 /vmfs/devices/disks/_device-ID ： Partition__*`

. 验证 VMFS 卷是否仅配置了 ATS ：
+
` * # vmkfstools -ph -v1 /vmfs/volumes/vmfs-volume-name*`

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


* 相关信息 *

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[过渡后使用 vSphere Client 重新挂载 VMFS 卷]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[过渡后使用 ESXi 命令行界面重新挂载 VMFS 卷]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html["VMware 文档"]
