---
permalink: san-host/task_remounting_luns_with_mount_point_using_dmmp_alias_name_on_linux_hosts_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, remount, lun, points, dmmp, alias, names 
summary: 从 7- 模式 ONTAP 过渡到集群模式 Data ONTAP 后，必须使用挂载点重新挂载 LUN 。7- 模式卷已脱机，并且主机无法访问 7- 模式 LUN 。 
---
= 重新挂载挂载点使用了 DMMP 别名的 LUN 过渡后的 Linux 主机
:icons: font
:imagesdir: ../media/


[role="lead"]
从 7- 模式 ONTAP 过渡到集群模式 Data ONTAP 后，必须使用挂载点重新挂载 LUN 。7- 模式卷已脱机，并且主机无法访问 7- 模式 LUN 。

如果要执行无副本过渡（ CFT ），则必须完成 `vol rehost` 的过程。

请参见 link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["《 7- 模式过渡工具无副本过渡指南》"] 了解详细信息。

* 对于基于副本的过渡（ CBT ），请在 7MTT 中完成存储转换操作后执行以下步骤。
* 对于 CFT ，请在 7MTT 中执行导入数据和配置操作后执行以下步骤。
+
.. 生成 7- 模式到 ONTAP LUN 的映射文件：
+
*** 对于基于副本的过渡，请从安装了 7MTT 的 Linux 主机运行以下命令： + ` * 过渡 CBT 导出 lunmap -p _project-name_ -o _file_path_*`
+
例如：

+
` * 过渡 CBT 导出 lunmap -p SanWorkLoad -o c ： /Libraires/Documents/7-C-LUN-mapping-csv*`

*** 对于无副本过渡，请在安装了 7MTT 的系统中运行以下命令： + ` * 过渡 CFT 导出 lunmap -p _project-name_ -s _svm-name_ -o _output-fil_`
+
例如：

+
` * 过渡 CFT 导出 lunmap -p SanWorkLoad -s svml -0 c ： /Libraries/Documents/7--to-C-LUN-mapping-svml.csv *`

+

NOTE: 您必须对每个 Storage Virtual Machine （ SVM ）运行此命令。



.. 记下 LUN 映射文件中的 ONTAP 设备句柄 ID 。
.. 删除为 7- 模式 LUN 创建的 SCSI 设备：
+
*** 要删除所有 SCSI 设备，请执行以下操作： + ` * rescan-scsi-bus.sh -r*`
*** 要单独删除每个 SCSI 设备，请执行以下操作： + ` * echo 1> /sys/block/_SCSI_ID__/delete_`
+
必须在所有 7- 模式 LUN SCSI 设备上执行此命令。请参见清单评估工作簿 _ 的 SAN 主机 LUN 选项卡上的 SCSI 设备 ID 列，以确定 LUN 的 SCSI 设备 ID 。



.. 发现新的 ONTAP LUN ：
+
` * 重新扫描 -scsi-bus.sh*`

.. 验证是否已发现 ONTAP LUN ：
+
` * sanlun lun show*`

+
ONTAP LUN 的 SCSI 设备应列在 `device filename` 列中。

+
例如， SCSI 设备名称是 ` /dev/sdp` 。

.. 在 ` /etc/multipath.conf` 文件中，将 7- 模式设备句柄 ID 替换为集群模式 Data ONTAP LUN 的设备句柄 ID ，以便 `别名` 指向集群模式 Data ONTAP LUN ID 。
+
您应按如下所示更新多路径部分。以下示例显示了在替换 7- 模式 LUN ID 之前的 ` /etc/multipath.conf 文件` 。在此示例中， LUN ID `360a9800037534562572b453855496b43` 指向 `dMMP_FS_LUN` 别名。

+
[listing]
----
multipaths {
        multipath {
             wwid	360a9800037534562572b453855496b43
             alias		dmmp_fs_lun
    }
}
----
+
将 7- 模式 LUN ID 替换为 ONTAP LUN ID `360a9800037534562572b453855496b43` 后，示例文件如下所示：

+
[listing]
----
multipaths {
        multipath {
             wwid	3600a098051764937303f4479515a7452
             alias		dmmp_fs_lun
    }
}
----
.. 为 ONTAP LUN 配置 DMMP 设备：
+
` * 多路径 *`

.. 验证 DMMP 别名是否指向 ONTAP LUN 设备句柄 ID ：
+
` * 多路径 -ll _device_handle_ID_*`

.. 将 ONTAP LUN 挂载到其挂载点目录：
+
` * 挂载 /dev/mapper/_alias_namemount_dir_name__*`

+
如果挂载点在 /etc/fstab 文件中定义，请使用 mount -a 命令挂载 LUN 。

.. 验证是否已挂载 DMMP 设备：
+
` 挂载 _`




