---
permalink: san-host/task_testing_data_luns_on_solaris_hosts_with_sun_volume_manager_svm_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, testing, data, solaris, sun, volume, manager, cutover, copy, based 
summary: 如果使用 7- 模式过渡工具 \ （ 7MTT\ ） 2.2 或更高版本以及 Data ONTAP 8.3.2 或更高版本过渡 Solaris 主机 ZFS 数据 LUN ，则可以在转换阶段之前测试已过渡的集群模式 Data ONTAP LUN ，以验证是否可以挂载 MPIO 设备。在测试期间，源主机可以继续对源 7- 模式 LUN 运行 I/O 。 
---
= 使用 Sun Volume Manager 测试 Solaris 主机上的数据 LUN 在基于副本的过渡的转换阶段之前
:icons: font
:imagesdir: ../media/


[role="lead"]
如果使用 7- 模式过渡工具（ 7MTT ） 2.2 或更高版本以及 Data ONTAP 8.3.2 或更高版本过渡 Solaris 主机 ZFS 数据 LUN ，则可以在转换阶段之前测试已过渡的集群模式 Data ONTAP LUN ，以验证是否可以挂载 MPIO 设备。在测试期间，源主机可以继续对源 7- 模式 LUN 运行 I/O 。

在开始测试阶段过渡之前，使用 Sun Volume Manager 数据 LUN 的源主机需要脱机。

新的集群模式 Data ONTAP LUN 必须映射到 测试主机和 LUN 必须已准备就绪 过渡

您应保持测试主机与源主机之间的硬件奇偶校验，并应在测试主机上执行以下步骤。

测试期间，集群模式 Data ONTAP LUN 处于读 / 写模式。测试完成后，它们将转换为只读模式，而您正在为转换阶段做准备。

.步骤
. 在生产主机上，禁用磁盘集：
+
` * metaset -s SVM -t*`

+
` * metaset -s SVM -a disable*`

+
` * metaset -s SVM -r*`

+
` * metaset -s SVM -P*`

+
` * 元集 *`

. 基线数据复制完成后，在 7MTT 用户界面（ UI ）中选择 * 测试模式 * 。
. 在 7MTT UI 中，单击 * 应用配置 * 。
. 在生产主机中，导入磁盘集：
+
` * metaimport – s _set-name_*`

+
[listing]
----
# metaimport -s svm
Drives in regular diskset including disk c0t60A98000383035356C2447384D39654Ad0:
  c0t60A98000383035356C2447384D39654Ad0
  c0t60A98000383035356C2447384D396548d0
More info:
  metaimport -r -v c0t60A98000383035356C2447384D39654Ad0


[22] 04:51:29 (root@sunx2-shu04) /
# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. 在测试主机上，重新扫描新的集群模式 Data ONTAP LUN ：
+
.. 确定 FC 主机端口（类型为 fc-fabric ）： + ` * #cfgadm – l*`
.. 取消配置第一个 fc-fabric 端口： + ` * #cfgadm – c 取消配置 c1*`
.. 配置第一个 fc-fabric 端口： + ` * #cfgadm – c unconfigure c2 *`
.. 对其他光纤通道端口重复上述步骤。
.. 显示有关主机端口及其连接设备的信息： + ` * # cfgadm – al*`
.. 重新加载驱动程序： + ` * # devfsadm – CV*`
+
` * # devfsadm – i iSCSI*`



. 验证集群模式 Data ONTAP LUN 是否存在：
+
` * sanlun lun show*`

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. 验证计划测试的 Sun Volume Manager 是否可导入：
+
` * metaimport – r – v*`

+
[listing]
----
# metaimport -r -v
Import: metaimport -s <newsetname> c5t600A0980383030444D2B466542485937d0
Device                                      offset       length replica flags
c5t600A0980383030444D2B466542485937d0           16         8192      a m     luo
c5t600A0980383030444D2B466542485936d0           16         8192      a       luo
----
. 导入具有新名称的元集：
+
` * metaimport – s _set-name disk-id_*`

+
disk-id 可从 `metaimport -r -v` 命令获取。

+
[listing]
----
# metaimport -s svm c5t600A0980383030444D2B466542485937d0
Drives in regular diskset including disk c5t600A0980383030444D2B466542485937d0:
  c5t600A0980383030444D2B466542485937d0
  c5t600A0980383030444D2B466542485936d0
More info:
  metaimport -r -v c5t600A0980383030444D2B466542485937d0
----
. 检查元集是否可用：
+
` * 元集 *`

. 运行文件系统检查：
+
` * fsck -F UFS /dev/mD/svm/rdsk/d1*`

. 使用 mount 命令手动挂载。
. 根据需要执行测试。
. 关闭测试主机。
. 在 7MTT UI 中，单击 * 完成测试 * 。


如果要将集群模式 Data ONTAP LUN 重新映射到源主机，则必须为源主机做好转换阶段的准备。如果集群模式 Data ONTAP LUN 仍要映射到测试主机，则无需在测试主机上执行其他步骤。
