---
permalink: san-host/task_remounting_dmmp_devices_on_linux_hosts_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, remount, dmmp, devices, linux, hosts 
summary: 从 7- 模式 ONTAP 过渡到集群模式 Data ONTAP 后，必须重新挂载 RHEL 5 和 RHEL 6 的 DMMP 设备。在挂载 DMMP 设备之前，主机无法访问 7- 模式 LUN 。 
---
= 过渡后重新挂载 Linux 主机上的 DMMP 设备
:icons: font
:imagesdir: ../media/


[role="lead"]
从 7- 模式 ONTAP 过渡到集群模式 Data ONTAP 后，必须重新挂载 RHEL 5 和 RHEL 6 的 DMMP 设备。在挂载 DMMP 设备之前，主机无法访问 7- 模式 LUN 。

如果要执行无副本过渡（ CFT ），则必须完成 vol rehost 的过程。请参见 link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["《 7- 模式过渡工具无副本过渡指南》"] 了解详细信息。

* 对于基于副本的过渡，请在 7- 模式过渡工具（ 7MTT ）中完成存储转换操作后执行以下步骤。
* 对于 CFT ，请在 7MTT 中的导入数据和配置操作完成后执行以下步骤。


.步骤
. 生成 7- 模式到 ONTAP LUN 的映射文件：
+
** 对于基于副本的过渡，请从安装了 7MTT 的 Linux 主机运行以下命令： + ` * 过渡 CBT 导出 lunmap -p _project-name_ -o _file_path_*`
+
例如：

+
` * 过渡 CBT 导出 lunmap -p SanWorkLoad -o c ： /Libraires/Documents/7-C-LUN-mapping-csv*`

** 对于无副本过渡，请在安装了 7MTT 的系统中运行以下命令： + ` * 过渡 CFT 导出 lunmap -p _project-name_ -s SVM-name -o _output-file_*`
+
例如：

+
` * 过渡 CFT 导出 lunmap -p SanWorkLoad -s svml -0 c ： /Libraries/Documents/7--to-C-LUN-mapping-svml.csv *`

+

NOTE: 您必须对每个 Storage Virtual Machine （ SVM ）运行此命令。



. 记下 LUN 映射文件中的新 ONTAP LUN 设备句柄 ID 。
. 删除为 7- 模式 LUN 创建的 SCSI 设备：
+
** 要删除所有 SCSI 设备，请执行以下操作： + ` * rescan-scsi-bus.sh -r*`
** 单独删除每个 SCSI 设备： + ` * echo 1> /sys/block/_SCSI_ID__/delete*`
+
必须在所有 7- 模式 LUN SCSI 设备上执行此命令。请参见清单评估工作簿 _ 的 SAN 主机 LUN 选项卡上的 SCSI 设备 ID 列，以确定 LUN 的 SCSI 设备 ID 。



. 发现新的 ONTAP LUN ：
+
` * 重新扫描 -scsi-bus.sh*`

. 验证是否已发现 ONTAP LUN ：
+
` * sanlun lun show*`

+
ONTAP LUN 的 SCSI 设备应列在 filename 列下。

. 为 ONTAP LUN 配置 DMMP 设备：
+
` * 多路径 *`

. 验证 DMMP 设备是否存在：
+
` * 多路径 -ll _lun_scsi_device_name_*`

+
在以下示例中， 3600a098051764937303f4479515a7451 表示 DMMP 设备句柄 ID ：

+
[listing]
----
[root@IBMx3550M3-229-169 ~]#multipath -ll /dev/sdq
3600a098051764937303f4479515a7451 dm-6 NETAPP,LUN C-Mode
----
. 挂载 LUN ：
+
` * 挂载 _device_name mountpoint_`

+
如果在 ` /etc/fstab` 文件中定义了挂载点，则可以运行 `mount -a` 命令挂载所有挂载点。

. 验证挂载点：
+
` * 挂载 *`


