---
permalink: copy-based/concept_how_you_can_use_assessment_executive_summary_for_transition_assessment.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, assessment, executive, summary 
summary: 过渡内容提要总结了环境中的 7- 模式控制器，主机和 FC 交换机。它提供了当前使用的特性和功能的评估报告，并为存储环境中的每个卷建议了过渡方法。您可以使用摘要来规划过渡。 
---
= 如何使用评估内容提要进行过渡 评估
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
过渡内容提要总结了环境中的 7- 模式控制器，主机和 FC 交换机。它提供了当前使用的特性和功能的评估报告，并为存储环境中的每个卷建议了过渡方法。您可以使用摘要来规划过渡。

内容提要包括以下主要部分：



== 目标集群

本节列出了您在评估期间选择的目标集群的 ONTAP 版本。



== 数据收集摘要

您可以查看已收集其信息的 7- 模式控制器，主机和交换机的列表。您可以查看 7- 模式控制器的 ONTAP 版本和型号详细信息。您还可以查看主机的操作系统类型，版本和型号。



== 过渡可行性和建议的过渡方法

本节总结了在每个控制器上运行的预检，以及在控制器和卷级别进行过渡的可行性。属于 vFiler 单元且处于 `s顶部` 或 `不一致` 状态的卷或脱机或受限的卷不会计入评估范围。此报告将显示针对每个控制器的预检中报告的错误和警告计数。过渡前，您应查看这些错误和警告并解决任何问题。有关这些预检的详细信息，请参见评估工作簿的配置预检摘要选项卡。

内容提要根据卷和控制器配置以及预检摘要，为每个评估卷提供了最佳过渡方法建议。例如，您无法过渡 7- 模式传统卷或 FlexCache 卷，因为 ONTAP 不支持这些功能。

对于大多数配置，建议使用 7- 模式过渡工具进行过渡。但是，某些工作负载无法使用 7- 模式过渡工具进行过渡，对于这些工作负载，您应使用基于应用程序或基于主机的迁移方法。

https://www.netapp.com/pdf.html?item=/media/19510-tr-4052.pdf["NetApp 技术报告 4052 ：《成功过渡到集群模式 Data ONTAP 》（ Data ONTAP 8.2.x 和 8.3 ）"^]



== 存储清单

本节提供以下信息：

* 存储对象：提供有关存储对象数量的信息，例如卷， qtree ， LUN ， vFiler 单元， 每个控制器中的 SnapMirror 关系，共享和导出。
* 存储利用率：提供有关 7- 模式控制器已用空间，可用空间和已用空间的信息。
* 许可证：提供在每个控制器上启用的功能许可证列表。
* 协议配置：提供有关在控制器上配置的协议的详细信息，例如 CIFS ， NFS 和 SAN 协议以及版本。
* SnapMirror 互连：提供有关作为 SnapMirror 关系源或目标的控制器或卷的信息。
+
您可以使用此信息确定与报告中列出的控制器存在 SnapMirror 关系但不包括在评估中的控制器。

* SnapVault 互连：提供有关作为与控制器中指定控制器，卷或 qtree 的 SnapVault 关系的源或目标的控制器，卷或 qtree 的信息。




== SVM 整合注意事项

如果您正在考虑将不同 vFiler 单元或 7- 模式控制器中的卷整合到一个 SVM ，则可以使用本节提供的信息确定 7- 模式系统是否绑定到不同的 Active Directory 域，是否具有不同的 NIS 配置， 具有相同的卷名称或 CIFS 共享名称，以及每个控制器中有多少本地用户和组。在整合不同 vFiler 单元或 7- 模式控制器以及规划过渡到单个 SVM 时，这些注意事项对于确定问题非常重要。



== 数据收集错误

本节详细介绍了 7- 模式过渡工具无法收集的控制器和主机信息以及故障原因。有关数据收集错误的详细信息，请参见评估工作簿的数据收集错误选项卡。您可以解决这些错误并重新评估系统。
