---
permalink: copy-based/concept_copy_based_transition_using_7mtt.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, 7, mode, tool 
summary: 通过 7- 模式过渡工具，您可以通过收集信息并评估要过渡的 7- 模式控制器，主机，交换机和应用程序来执行基于副本的过渡。然后，您可以将数据和配置从 7- 模式迁移到 ONTAP 。 
---
= 使用 7- 模式过渡工具进行基于副本的过渡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 7- 模式过渡工具，您可以通过收集信息并评估要过渡的 7- 模式控制器，主机，交换机和应用程序来执行基于副本的过渡。然后，您可以将数据和配置从 7- 模式迁移到 ONTAP 。

7- 模式过渡工具可在 Windows 或 Linux 系统上运行。7- 模式过渡工具提供了一个 Web 界面和一个命令行界面，用于管理过渡操作。



== 收集和评估 ONTAP 系统，主机，交换机和应用程序

您可以使用 7- 模式过渡工具执行以下收集和评估任务：

* 从 ONTAP 系统（集群中的 7- 模式控制器和节点），主机，交换机和主机应用程序收集清单信息。
* 生成 FC 分区计划以配置分区，以便对启动程序主机和目标进行分组。
* 评估 7- 模式系统的特性和功能，并确定这些特性和功能在选择进行过渡的 ONTAP 版本中的工作原理。




== 将数据和配置从 7- 模式移动到 ONTAP

基于副本的过渡使用 SnapMirror 技术将 7- 模式卷和配置从 Data ONTAP 7G 和 7- 模式复制到 ONTAP 。

您可以使用 7- 模式过渡工具执行以下任务，以执行基于副本的迁移：

* 将一组 7- 模式独立卷或一组卷 SnapMirror 关系中的 7- 模式卷从运行不同 7- 模式版本的系统迁移到 ONTAP 8.2.x 及更高版本支持的任何版本。
* 对过渡项目中包含的卷运行预检，以验证其过渡兼容性并查看可能的更正操作。
* 在断开客户端访问之前，将 7- 模式配置应用于 ONTAP ，从而减少停机时间。
+
基于副本的过渡支持 NAS 和 SAN 配置的过渡。

+

NOTE: 仅支持将 SAN 过渡到 ONTAP 8.3 及更高版本支持的版本。



* 相关信息 *

xref:concept_requirements_for_copy_based_transition.adoc[基于副本的过渡的要求]
