---
permalink: copy-based/concept_restrictions_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, restrictions 
summary: 您必须了解过渡某些 7- 模式卷和配置时的某些限制。 
---
= 过渡限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解过渡某些 7- 模式卷和配置时的某些限制。

* 只有在同一项目中的所有卷完成基线传输后，才能转换同一项目中的任何卷。
* 如果要在 7- 模式源卷和目标卷都运行 Data ONTAP 7.3.x 或 8.0.x 时过渡 7- 模式主卷和二级卷，则只有在 7- 模式主卷没有数据更新时，才必须开始过渡 7- 模式二级卷。
+
您必须确认 7- 模式主卷到 7- 模式二级卷的数据更新计划与 7- 模式二级卷到 ONTAP 二级卷的计划不冲突。

* 在 7- 模式系统或集群上的聚合从 32 位升级到 64 位格式时，不得启动过渡；否则过渡将失败。
* 7- 模式过渡工具不会过渡 qtree 作为 qtree SnapMirror 关系目标的卷。
+
必须先断开 qtree SnapMirror 关系，然后才能过渡卷。

* 您不能使用 7- 模式过渡工具 Web 界面过渡扇出 SnapMirror 关系（与不同控制器中多个二级卷存在 SnapMirror 关系的主卷）。
+
要过渡扇出配置中的 SnapMirror 关系，必须使用 7- 模式过渡工具 CLI 。您应该为每个二级卷创建单独的项目，完成二级项目的过渡，然后创建并完成主卷的过渡。

* 您不能同时将卷从不同的 vFiler 单元或不同的 7- 模式控制器过渡到同一个 SVM 。
+
您必须先完成从给定 vFiler 单元或 7- 模式控制器的卷过渡，然后才能开始从另一个 vFiler 单元或 7- 模式控制器过渡卷。

* 7- 模式过渡工具不会将 vFiler 单元作为单个实体进行过渡。
+
但是，您可以通过选择 vFiler 单元中的所有卷作为一个或多个项目的一部分来过渡这些卷。

* 如果根卷基于属于默认 vFiler 单元的 qtree ，则 7- 模式过渡工具不会过渡 vFiler 单元的根卷。
* 如果卷和 qtree 属于不同的 vFiler 单元，则 7- 模式过渡工具不会过渡具有 qtree 的卷。
+
过渡此类卷会导致无法访问 qtree 。



预检操作将显示有关其中某些限制的信息。
