---
permalink: copy-based/concept_considerations_for_deduplication_and_compression.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, deduplication, compression 
summary: 使用数据压缩时，源卷和目标卷必须属于 64 位聚合。在过渡期间，源卷上的所有数据压缩和重复数据删除节省的空间都会通过网络保留下来。过渡后，目标卷将从源卷继承所有数据压缩和重复数据删除属性以及存储节省。 
---
= 重复数据删除和数据压缩注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用数据压缩时，源卷和目标卷必须属于 64 位聚合。在过渡期间，源卷上的所有数据压缩和重复数据删除节省的空间都会通过网络保留下来。过渡后，目标卷将从源卷继承所有数据压缩和重复数据删除属性以及存储节省。

过渡经过重复数据删除和压缩的数据有助于在过渡期间减少网络带宽，原因如下：

* 共享块仅传输一次。
* 数据压缩在整个传输过程中保持不变。
* 由于数据压缩和重复数据删除节省了空间，因此数据压缩和重复数据删除所涉及的传输大小会更小；因此，传输完成速度会更快。


过渡期间，不应对源卷上的现有数据启动数据压缩或重复数据删除。如果正在进行重复数据删除或数据压缩，则只有在完成重复数据删除或数据压缩操作后，才应开始过渡。因此，未经过重复数据删除或未压缩的数据以及其他临时元数据文件不会通过网络发送到目标卷。

要使重复数据删除和数据压缩对写入到 ONTAP 卷上的任何新数据生效，必须在过渡后启用重复数据删除和数据压缩计划。

从 Data ONTAP 8.1 开始，重复数据删除会在卷中保留一个部分顺序的指纹数据库以及聚合副本。因此，目标系统将从源卷节省空间，并获得订购指纹数据库的副本。迁移后，当首次在新卷上运行卷效率时，聚合指纹数据库会自动通过目标卷中的副本构建。这可能会一次性增加完成卷效率操作所需的时间。

如果源卷运行的是在 8.1 之前的 7- 模式下运行的 Data ONTAP ，则必须使用 ` -scan-old-data option` 参数运行 `volume efficiency start` 命令以优化空间节省。迁移完成后，您应验证重复数据删除计划是否满足集群上的要求，并考虑切换到卷效率策略。
