---
permalink: copy-based/task_creating_a_transition_project.html 
sidebar: sidebar 
keywords: create, transition, project, ontap, copy, based, transition 
summary: 创建过渡项目包括选择 7- 模式卷并将其映射到 Storage Virtual Machine （ SVM\ ），映射接口以及为 SnapMirror 关系创建数据复制计划。 
---
= 创建过渡项目
:icons: font
:imagesdir: ../media/


[role="lead"]
创建过渡项目包括选择 7- 模式卷并将其映射到 Storage Virtual Machine （ SVM ），映射接口以及为 SnapMirror 关系创建数据复制计划。

您必须已在集群上创建所需的 SVM 。

项目中的所有卷都会迁移到同一个 SVM 。如果要将卷迁移到不同的 SVM ，则必须创建多个项目。

如果目标集群运行的是 Data ONTAP 8.3.1 或更早版本，并且您希望在读 / 写模式下对 NAS 卷运行预转换操作，则必须为 NAS 卷和 SAN 卷创建单独的项目。需要执行此操作，因为如果项目中包含 SAN 卷，则不支持预转换读 / 写模式。

如果项目包含 SnapLock Compliance 卷，并且您希望对非 SnapLock Compliance 卷以读 / 写模式运行预转换操作，则必须为 SnapLock Compliance 卷和非 SnapLock Compliance 卷创建单独的项目。需要执行此操作，因为如果项目中包含 SnapLock Compliance 卷，则不支持预转换读 / 写模式。

.步骤
. 从主页中选择 * 基于副本的过渡 * 迁移方法，然后单击 * 开始规划 * 。
+
如果尚未添加新项目所需的控制器和集群，您可以在输入设备凭据窗格中输入详细信息。

. 确认已将在 7- 模式系统和 ONTAP 系统中运行的所有必需 Data ONTAP 添加到该工具中，然后单击 * 下一步 * 。
+
此时将显示选择源卷页面。

. 选择要过渡的 7- 模式卷。
+
.. 从 7- 模式控制器窗格中，选择要从中添加卷的 7- 模式控制器或 vFiler 单元。
.. 添加要包含在项目组中的卷：
+
|===
| 要过渡的内容 | 那么 ... 


 a| 
独立卷
 a| 
为要过渡的卷选择 * 过渡为独立 * 。

如果从此列中选择第一个卷，则会创建一个独立项目。



 a| 
卷 SnapMirror 关系
 a| 
... 为所有主卷选择 * 使用 SnapMirror 关系过渡 * 。
+
此时将创建两个项目：一个用于主卷的主项目和一个二级项目。

... * 可选： * 如果项目中不包括二级控制器，请在需要其他存储系统凭据对话框中输入控制器的详细信息。


|===
+
如果卷中至少有一个 LUN ，则卷类型将显示为 SAN 。

+
卷名称上提供的超链接将打开一个对话框，其中列出了卷中的 qtree 和 LUN 及其属性。

+

TIP: 最佳做法是，一个项目中的所有卷都具有相同的定义（独立卷，主卷或二级卷）。例如，项目应包含所有独立卷，而不是混合使用独立和 SnapMirror 关系。

.. 选择要包括在项目中的所有卷后，单击 * 创建项目并继续 * ，在显示的对话框中输入项目名称和项目组详细信息，然后单击 * 保存 * 以创建项目。


. 选择要用于 SnapMirror 数据复制的 7- 模式 IP 地址和多路径 IP 地址。
+
.. 输入 7- 模式数据复制 IP 地址。
+
默认情况下，此字段会预先填充 7- 模式系统的管理 IP 地址。如果需要，您可以将此 IP 地址更改为具有数据复制权限的任何有效 IPv4 地址。

.. 如果要使用多个路径对数据传输进行负载平衡，请在 IP 配置窗格中输入一个 IP 地址，然后单击 * 下一步 * 。


. 从选择 SVM 页面中，选择目标集群和 SVM ，然后按照以下步骤进行操作：
+
.. 通过单击选择集群模式 Data ONTAP 系统下拉列表中的集群名称来选择目标集群。
+
此时将在选择 SVM 窗格中加载 SVM 。

.. 从选择 SVM 窗格中选择要过渡卷的目标 SVM 。
.. 单击 * 下一步 * 。


+
要在 ONTAP 中将 7- 模式卷过渡到 MetroCluster 配置， SVM 子类型必须为 `sync-source` 。

+
+ 如果选择属于集群模式 Data ONTAP 8.2 的 SVM ，则会显示一个对话框，确认是否在 7- 模式存储系统上配置了本地用户和组或 CIFS 共享或文件。7- 模式过渡工具不支持将本地用户和组过渡到集群模式 Data ONTAP 8.2 。如果您有本地用户和组，则可以选择属于 ONTAP 8.2.1 及更高版本支持的 SVM 。

. 在 SVM 审核日志目标路径对话框中，输入目标 SVM 上的路径，以便从 7- 模式存储系统过渡审核配置。
+
此路径用于将审核日志保存在 ONTAP 系统中。

. 从映射卷页面中，选择要过渡的目标卷，以便将每个源卷映射到所需的聚合。
+
.. 从将原始卷映射到目标集群上的聚合窗格中，选择必须将 7- 模式卷复制到的聚合。
.. 要更改集群上目标卷的名称，请在 * 目标卷 * 字段中输入其他名称。
.. 单击 * 下一步 * 。


+
如果项目中包含的所有卷和 qtree 都配置为仅提供 NFS 请求，则不必提供审核路径，因为审核配置不会过渡（即使提供了审核路径，也会忽略此输入）。

. 在网络配置窗格中，提供有关必须在 SVM 上创建的 LIF 的信息。
+

NOTE: 无法过渡 FC 和 iSCSI LIF 。您必须在 SVM 上手动创建它们。

+
|===
| 如果您要 ... | 那么 ... 


 a| 
过渡现有的 7- 模式 IP 地址
 a| 
.. 单击 * 选择 7- 模式 LIF* 。
.. 选择所需的 7- 模式 IP 地址，并提供目标节点和目标端口详细信息。
.. 单击 * 保存 * 。




 a| 
创建新的 LIF
 a| 
.. 单击 * 添加新 LIF* 。
.. 在显示的对话框中，输入新 LIF 的详细信息。
.. 单击 * 保存 * 。


|===
+
要在成功过渡后提供网络连接，您必须将 7- 模式 IP 地址过渡到 ONTAP 中类似的网络拓扑。例如，如果在物理端口上配置了 7- 模式 IP 地址，则应将 IP 地址过渡到 ONTAP 中的相应物理端口。同样，在 VLAN 端口或接口组上配置的 IP 地址应过渡到 ONTAP 中的相应 VLAN 端口或接口组。

. 添加所有必需的 IP 地址后，单击 * 下一步 * 。
. 在配置计划页面中，配置基线和增量传输的数据复制计划，并发卷 SnapMirror 传输的数量以及要过渡的 SnapMirror 传输的限制。
+
您可以提供数据复制计划和限制，以有效管理灾难恢复和过渡数据复制操作。您可以创建多个计划，每个项目最多有七个计划。例如，您可以为工作日和周末创建自定义计划。

+

NOTE: 这些计划将根据源 7- 模式控制器时区生效。

+
.. 在配置计划窗格中，单击 * 创建计划 * 。
.. 在创建数据复制计划对话框中，输入新计划的名称。
.. 在重复天数窗格中，选择 * 每日 * 或 * 选择天数 * 以指定应运行数据复制操作的日期。
.. 在时间间隔窗格中，指定数据传输的 * 开始时间 * 和 * 持续时间 * 。
.. 在时间间隔窗格中，指定增量传输的 * 更新频率 * 或选择 * 持续更新 * 。
+
如果启用持续更新，则更新开始时的最小延迟为 5 分钟，具体取决于并发 SnapMirror 传输的可用性。

.. 在 "Parameters for Transition Data Copy Operations （ based on Volume SnapMirror ） " （过渡数据复制操作的参数（基于卷 SnapMirror ））窗格中，指定并发卷 SnapMirror 传输的最大数量（以运行时可用 SnapMirror 传输的百分比和数字表示）以及限制（项目中所有卷的最大带宽）。
+

NOTE: 字段中提供的默认值为建议值。更改默认值时，必须分析 7- 模式 SnapMirror 计划，并确保提供的值不会影响这些计划。

.. 单击 * 创建 * 。
+
新计划将添加到过渡计划窗格中。

.. 添加所有必需的数据复制计划后，单击 * 下一步 * 。


. 如果要过渡 SnapLock 卷，请规划过渡后需要验证监管链的卷。
+
.. 选择需要验证监管链的源 SnapLock 卷。
+
只有读 / 写 7- 模式 SnapLock 卷才支持监管链验证过程，只读卷不支持监管链验证过程。监管链验证仅支持文件名包含 ASCII 字符的 SnapLock 卷。

.. 提供有关用于存储在监管链验证操作期间生成的指纹数据的 ONTAP 卷的详细信息。
+
ONTAP 卷必须已位于指定的 SVM 上。

.. 单击 * 下一步 * 。




* 相关信息 *

xref:concept_guidelines_for_creating_a_data_copy_schedule.adoc[创建数据复制计划的注意事项]

xref:task_creating_schedule_for_snapmirror_transfers.adoc[为 SnapMirror 传输创建数据复制计划]

xref:concept_managing_snapmirror_transfers_and_schedule.adoc[管理 SnapMirror 传输和计划]

xref:task_transitioning_volumes_by_excluding_a_subset_of_configurations.adoc[使用命令行界面自定义 7- 模式配置的过渡]

xref:task_managing_logical_interfaces.adoc[管理逻辑接口]

xref:task_removing_volumes_from_a_project.adoc[从项目中删除卷]
