---
permalink: copy-based/task_starting_baseline_data_copy.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, baseline, copy 
summary: 创建项目并完成预检操作后，必须启动从 7- 模式卷到 ONTAP 的数据复制。您可以为单个项目启动基线数据复制操作。在数据复制期间，您应停止不必要的系统进程和网络活动。 
---
= 正在启动基线数据复制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建项目并完成预检操作后，必须启动从 7- 模式卷到 ONTAP 的数据复制。您可以为单个项目启动基线数据复制操作。在数据复制期间，您应停止不必要的系统进程和网络活动。

您必须已创建至少一个数据复制计划。

您可以通过执行测试迁移来估算完成基线传输所需的时间，并评估卷 SnapMirror 传输在您的环境中实现的性能。以下是可能影响性能的一些因素：

* 已选择过渡数据复制计划选项
+
此计划控制 SnapMirror 并发传输的最大数量和传输所使用的最大带宽。

* 支持的并发卷 SnapMirror 传输的最大数量 7- 模式源控制器
* 7- 模式源控制器和 ONTAP 目标控制器之间的网络带宽
+
必须最大限度地减少与迁移活动无关的网络流量，以便最大程度地提高源系统和目标系统之间的吞吐量并最大限度地缩短响应时间。

* 源控制器和目标控制器的性能
+
源系统和目标系统应具有最佳的 CPU 利用率和可用内存。

* 数据期间发生的 7- 模式卷 SnapMirror 传输的数量 复制


.步骤
. 从信息板中，选择要为其启动基线数据复制的项目。
. 单击 * 启动基线 * 。
+
预检将在后台再次运行，如果未检测到错误，则会根据数据复制计划启动基线传输。操作进度对话框显示有关基线数据复制期间运行的预检操作的状态的信息。

. 单击 * 卷 * 选项卡可查看基线传输的状态和进度。
+
要查看每个卷的详细 SnapMirror 详细信息，可以单击 * 查看过渡详细信息 * 。并发 SnapMirror 传输的数量取决于当前活动的计划中提供的输入。您可以从信息板上的数据复制计划选项卡跟踪活动计划。

+
基线数据复制操作完成后，将根据创建项目时提供的计划开始增量 SnapMirror 更新。



* 相关信息 *

xref:task_creating_schedule_for_snapmirror_transfers.adoc[为 SnapMirror 传输创建数据复制计划]
