---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: 7- 模式过渡
    url: "/index.html"
  - title: 发行说明
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: 法律声明
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 新增功能
      summary: 查看最新版本的 7- 模式中的新增功能 过渡工具
      url: releasenotes.html
    - title: 安装 7- 模式过渡工具
      summary: 了解如何在 Microsoft Windows 或上安装此工具 Linux
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: 收集过渡所需的数据
      summary: 了解如何收集对过渡至关重要的信息
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: 适用于 7- 模式管理员的命令映射
    links:
    - title: 7- 模式命令与 ONTAP 命令的映射关系
      summary: 查找与 7- 模式命令等效的 ONTAP
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: 7- 模式选项与 ONTAP 命令的映射关系
      summary: 了解 7- 模式选项如何映射到 ONTAP 命令参数
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: 7- 模式配置文件如何映射到 ONTAP 命令
      summary: 了解 7- 模式配置文件与 ONTAP 配置命令的映射关系
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: 过渡方式
    links:
    - title: 基于副本的过渡
      summary: 使用工具从 7- 模式执行基于副本的过渡 到 ONTAP
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: 无副本过渡
      summary: 使用工具从 7- 模式执行无副本过渡 到 ONTAP
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: 使用 SnapMirror 过渡数据
      summary: 了解如何使用将数据从 7- 模式过渡到 ONTAP snapmirror 命令
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: SAN 主机过渡和修复
    links:
    - title: VMware ESXi
      summary: 了解 VMware ESXi 主机的过渡前和过渡后要求
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux
      summary: 了解 Red Hat Enterprise 的过渡前和过渡后要求 Linux 主机
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Windows
      summary: 了解 Microsoft Windows 主机的过渡前和过渡后步骤
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 所有ONTAP 产品文档
