---
permalink: copy-free/concept_aggregate_space_considerations_during_transition.html 
sidebar: sidebar 
keywords: transition, copy, free, aggregate, space, requirements 
summary: 过渡之前，必须确保 7- 模式聚合具有足够的可用空间。7- 模式过渡工具会根据物理空间，逻辑空间， Snapshot 副本占用的空间以及空间保证设置对聚合执行各种空间检查。此外，您还必须了解 Flash Pool 聚合的空间注意事项。 
---
= 过渡时的聚合空间要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
过渡之前，必须确保 7- 模式聚合具有足够的可用空间。7- 模式过渡工具会根据物理空间，逻辑空间， Snapshot 副本占用的空间以及空间保证设置对聚合执行各种空间检查。此外，您还必须了解 Flash Pool 聚合的空间注意事项。



== 聚合中的物理空间

如果 7- 模式聚合中的可用空间小于物理空间的 5% ，则过渡将被阻止。最佳实践是，过渡前，在 7- 模式聚合中至少有 20% 的可用空间。

由于以下原因，聚合中需要额外空间：

* 在期间为每个 7- 模式聚合创建聚合级别 Snapshot 副本 导出阶段
* 使用新数据在过渡后的聚合上测试工作负载 在预生产测试阶段


如果没有额外空间，则可以在过渡前向 7- 模式系统添加磁盘。如果添加磁盘不可行，或者您可以确保在预生产阶段仅在过渡后的卷上写入有限数量的数据，则可以使用 7- 模式过渡工具确认此错误并继续过渡。但是，您必须在过渡期间继续监控聚合空间，并确保聚合在预生产测试阶段不会增长。



== 聚合中的逻辑空间

如果 7- 模式聚合中的逻辑空间已满 97% 以上，则 7- 模式过渡工具会在预检期间引发阻塞错误。您可以在规划阶段忽略此错误并继续过渡； 但是，您必须通过减小此类聚合中的卷大小或向聚合添加更多磁盘来确保在执行导出并暂停操作之前已用逻辑空间小于 97% 。您不能在导出和暂停阶段忽略此错误。



== Snapshot 溢出

如果 7- 模式聚合中的 Snapshot 副本占用的空间超过为 Snapshot 副本预留分配的空间，则在导出并暂停操作中创建聚合级 Snapshot 副本可能会失败。7- 模式过渡工具在对此情况进行预检期间引发阻塞错误。在这种情况下，您必须在规划阶段删除所有现有的聚合级别 Snapshot 副本。

如果您不想删除现有 Snapshot 副本，则可以在规划阶段忽略此错误并继续过渡；但是，在执行导出并暂停操作之前，必须确保 Snapshot 副本的已用容量百分比小于 100% 。



== 空间保证设置

如果 7- 模式控制器中的卷具有以下空间保证设置，则 7- 模式过渡工具会在预检期间引发阻止错误：

* 禁用了保证的卷保证卷
* 文件保证卷
* * 禁用保证的卷保证卷 *
+
在某些情况下，由于聚合中缺少空间，卷保证卷的空间保证将被禁用。

+
您必须在 7- 模式聚合上创建足够的可用空间，然后使用以下 7- 模式命令为此类 7- 模式卷启用空间保证：

+
` * vol options _volume_name_ guarantee volume*`

+
如果您不想对 7- 模式执行任何更正操作，可以忽略此错误。过渡后，请检查已禁用保证的卷，并使用以下命令手动启用保证：

+
` * volume modify -vserver -volume -space-guarantee volume*`

* * 文件保证卷 *
+
ONTAP 不支持文件保证。

+
如果您有文件保证卷，则必须执行以下操作之一：

+
** 如果 7- 模式卷包含空间预留的 LUN 或文件，请使用 7- 模式命令将卷的空间保证类型更改为 volume ： + ` * vol options _volume_name_ guarantee volume*`
+
在运行此命令之前，必须确保 7- 模式聚合上有足够的可用空间。

** 如果 7- 模式卷不包含任何预留空间的 LUN 或文件，请使用以下 7- 模式命令将卷的空间保证更改为 none ： + ` * vol options _volume_name_ guarantee none*` 如果您不想对 7- 模式执行任何更正操作，则可以忽略此错误并继续过渡。


+
过渡期间，如果这些卷包含预留了空间的 LUN 或文件，则其空间保证将自动转换为 `volume` ，但空间保证最初将被禁用。您必须在聚合上创建足够的可用空间，然后使用以下命令手动启用保证：

+
+ ` * volume modify -vserver -volume -space-guarantee volume*`

+
+ 如果卷不包含任何空间预留的 LUN 或文件，则在过渡期间，其空间保证将自动转换为 none 。





== 有关 Flash Pool 聚合的其他注意事项

如果 Flash Pool 聚合的 SSD 中的可用空间小于 SSD 总磁盘空间的 5% ，则不支持过渡。要继续过渡，您必须禁用 SSD 缓存或添加更多 SSD 。

* 相关信息 *

xref:reference_ignorable_errors_during_transition.adoc[过渡期间发生可忽略的错误]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁盘和聚合管理"]
