---
permalink: copy-free/concept_restrictions_during_preproduction_testing.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, preproduction, testing, restrictions 
summary: 在预生产测试期间，某些操作会被阻止，某些操作不建议执行。如果您不想提交过渡，则可以将这些限制回滚到 7- 模式。 
---
= 预生产测试期间的限制
:icons: font
:imagesdir: ../media/


[role="lead"]
在预生产测试期间，某些操作会被阻止，某些操作不建议执行。如果您不想提交过渡，则可以将这些限制回滚到 7- 模式。



== 已阻止的操作

|===
| 操作 | 说明 


 a| 
自动删除（自动删除）聚合 Snapshot 副本
 a| 
由于回滚时需要使用在导出操作期间创建的 7- 模式聚合级别 Snapshot 副本，因此聚合中的已用空间增长时不会自动删除这些 Snapshot 副本。


IMPORTANT: 您必须监控聚合中的可用物理空间，并确保聚合在测试期间不会用尽空间。



 a| 
将卷移动到另一个聚合
 a| 
* 您不能将卷移动到过渡后的聚合。
* 您可以将卷从过渡后的聚合移动到集群中的聚合。




 a| 
在卷之间复制或移动 LUN
 a| 
* 您不能将 LUN 复制或移动到过渡后的卷。
* 您可以将 LUN 从过渡后的卷复制或移动到集群中的其他卷。




 a| 
创建聚合
 a| 
此操作在目标集群 HA 对上受限。您可以在集群中的其他节点上创建聚合。



 a| 
销毁聚合
 a| 
由于回滚时需要使用在导出操作期间创建的 7- 模式聚合级别 Snapshot 副本，因此无法销毁过渡后的聚合。



 a| 
将过渡后的聚合设置为根聚合
 a| 
过渡后的聚合不能选择为根聚合。此外，您不能将过渡后的聚合的 HA 策略修改为 CFO 。



 a| 
执行文件复制操作
 a| 
* 您不能将文件（单个文件按需复制）移动或复制到过渡后的卷。
* 您可以将过渡后的卷中的文件移动或复制到集群中的其他卷。




 a| 
镜像现有聚合
 a| 
此操作会在集群中的所有聚合上被阻止。



 a| 
升级或还原目标上的 Data ONTAP 版本 集群节点
 a| 
在升级或还原目标集群节点之前，您必须提交项目。



 a| 
添加磁盘
 a| 
您不能在管理权限级别运行 `storage aggregate add-disks` 命令。但是，您可以在高级权限级别运行此命令。


IMPORTANT: 您必须确保仅添加 7- 模式磁盘架中的备用磁盘，以增加过渡后聚合中的空间。您必须使用 ` -disklist` 参数添加备用磁盘（不得使用 ` -diskcount` 参数）。



 a| 
将过渡后的卷指定为 SVM 根卷
 a| 
您不能对过渡后的卷运行 `volume make-vsroot` 命令。

|===


== 不建议执行的操作

|===
| 操作 | 回滚前的更正操作 


 a| 
重新定位聚合

过渡后的聚合的所有权将更改为其 HA 配对项。
 a| 
回滚前交换聚合所有权，因为 7- 模式过渡工具会根据项目中保存的目标节点映射信息将聚合映射到 7- 模式控制器。



 a| 
在过渡后的聚合上创建卷
 a| 
您必须删除这些卷或将其移动到其他聚合。



 a| 
重命名聚合或卷
 a| 
将聚合或卷重命名为其原始名称。



 a| 
更改 RAID 类型
 a| 
如果决定回滚到 7- 模式，则 RAID 类型必须与 7- 模式 RAID 类型匹配。

|===
* 相关信息 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"]
