---
permalink: copy-free/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, cifs, local, users, group 
summary: 迁移 CIFS 本地用户和组时，您必须了解运行过渡操作的注意事项。 
---
= 过渡 CIFS 本地用户和组的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
迁移 CIFS 本地用户和组时，您必须了解运行过渡操作的注意事项。

* 不支持将 CIFS 数据提供卷从具有本地用户和组的 7- 模式控制器或 vFiler 单元过渡到具有非 BUILTIN CIFS 本地用户和组的 SVM 。
+
要进行过渡， SVM 只能具有 BUILTIN CIFS 本地用户和组。

* 您必须确保 7- 模式中的本地用户和组数量不超过 ONTAP 的本地用户和组限制。
+
如果 7- 模式中的本地用户和组数量超过 ONTAP 中定义的限制，您必须联系技术支持。

* 在 7- 模式系统中，密码为空的本地用户帐户或密码超过 14 个字符的本地用户帐户将过渡到密码为 ` * cifsUser@1*` 的 ONTAP 软件。
+
过渡完成后，您可以使用密码 ` * cifsUser@1*` 从 Windows 系统访问这些用户。然后，您必须使用以下命令手动更改 SVM 上此类 CIFS 本地用户的密码：

+
` * cifs users-and-groups local-user set-password -vserver _svm_name_ -user-name _user_name_*` 。

* 如果无法从目标 ONTAP 软件访问 7- 模式过渡工具 IP 地址，则 7- 模式过渡工具会阻止在预检阶段将 CIFS 本地用户和组过渡到 ONTAP 软件。如果您在预检阶段发现此错误，请使用
+
` * 网络 ping -node local -destination _ip_address_*`

+
命令以确保可从目标 ONTAP 软件访问 7- 模式过渡工具 IP 地址。您可以编辑随 7- 模式过渡工具安装的 ` \etc\conf\transition-tool.conf` 文件，以修改该工具使用的任何配置选项，例如 7- 模式过渡工具 IP 地址。

* 要将本地用户和组过渡到的 SVM 必须具有数据 LIF 。
* 如果本地组将多个成员系统标识符（ SID ）映射到 7- 模式系统上的单个域用户或组，则 7- 模式过渡工具会阻止在预检阶段将本地用户和组过渡到 ONTAP 。
+
如果您在预检阶段看到此错误，则必须手动删除映射到 7- 模式系统上的单个域用户或组的其他 SID 。然后，您必须重新运行预检操作，并且仅将一个 SID 映射到域用户或组。

+
https://["故障排除工作流： CIFS ：连接到系统的设备无法正常运行"]



* 相关信息 *

http://["SMB/CIFS 管理"]
