---
permalink: copy-free/reference_ignorable_errors_during_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, ignorable, errors 
summary: 过渡期间，您可能会遇到一些可忽略的错误。在无副本过渡项目的预检，布线，导入或提交操作期间，可能会发生这些错误。在继续过渡之前，您必须确认这些错误。 
---
= 过渡期间发生可忽略的错误
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
过渡期间，您可能会遇到一些可忽略的错误。在无副本过渡项目的预检，布线，导入或提交操作期间，可能会发生这些错误。在继续过渡之前，您必须确认这些错误。

如果使用 7- 模式过渡工具命令行界面将任何可忽略的错误类别添加到无副本过渡项目，则表示您已了解此错误的影响。忽略此错误后，您必须重新运行过渡操作。此时，阻止错误将更改为警告消息，此错误将显示为 "`acknowledged` " 。您可以在出现警告的情况下继续过渡。



== 预检操作：可忽略的错误类别

|===
| 类别 | 显示错误时 


 a| 
`ignore-source-not-multipath`
 a| 
7- 模式磁盘架不采用多路径配置。



 a| 
`ignore-target-not-multipath`
 a| 
目标集群节点中的磁盘架不采用多路径配置。



 a| 
`ignore-source-storage-fault`
 a| 
7- 模式磁盘架存在一些故障（如 `storage show fault` 命令的输出所示）。



 a| 
`ignore-target-storage-fault`
 a| 
目标集群节点中的磁盘架出现某些故障（如 `ssystem node run -node _node_name_ -command storage show fault` 命令的输出所示）。



 a| 
ignore-target-port-requirement
 a| 
目标集群节点没有足够数量的端口可用于连接 7- 模式磁盘架。



 a| 
`ignore-aggr-space-less -than -5-percent`
 a| 
7- 模式聚合空间不足，因为 7- 模式聚合中的可用空间不到物理空间的 5% 。



 a| 
`ignore-aggr-logical-space-more-more-than -97%`
 a| 
7- 模式聚合空间不足，因为聚合中的逻辑空间已满 97% 以上。



 a| 
`ignore-aggr-snapshot-sc泄露 -more-than -4-percent`
 a| 
7- 模式聚合空间不足，因为 Snapshot 副本占用的空间超过为 Snapshot 副本预留分配的空间。



 a| 
`ignore-aggr-physical-space-more-mor-on-89-percent-and-snapshot-sc泄露`
 a| 
7- 模式聚合空间不足，因为已用物理空间总量超过 89% ，并且 Snapshot 副本占用的空间超过为 Snapshot 副本预留分配的空间。



 a| 
`ignore-volume-with -file-gurantee`
 a| 
7- 模式卷的空间保证设置为 `file` ，这在 ONTAP 中不受支持。



 a| 
`ignore-volume-with -disable-gurantees`
 a| 
由于卷中缺少空间，当前已禁用卷的空间保证。



 a| 
`nfs-qtree-exported`
 a| 
7- 模式系统中存在 qtree 导出规则。

确认此错误意味着您已了解在 7- 模式下运行的 Data ONTAP 与 ONTAP 之间 qtree 导出规则的差异。在 7- 模式过渡工具应用 NFS 导出规则后，您可能需要执行一些手动步骤。

https://["7MTT预检10111 -过渡具有qtree级别导出的7-模式卷"]



 a| 
`ignore-configuration-limits-check`
 a| 
要过渡的对象和配置超出特定限制。存储转换可能需要很长时间，您必须为停机做好准备。

https://["在无副本过渡期间缩短存储转换时间的注意事项"]



 a| 
`ignore-cifs-ad-domain-mismatch`
 a| 
即使 7- 模式系统的 CIFS Active Directory 域与目标 SVM 的 CIFS Active Directory 域不同， 7- 模式过渡工具仍会继续过渡 CIFS 配置。

您必须确保 7- 模式系统的 CIFS Active Directory 域和目标 SVM 是受信任的域。否则，将 CIFS 配置过渡到目标 SVM 将失败。

https://["如何在 Active Directory 域为时过渡 CIFS 配置 7- 模式和目标 SVM 上的 CIFS 服务器不同"]

|===


== 布线验证操作：可忽略的错误类别

|===
| 类别 | 显示错误时 


 a| 
`ignore-missing-spare-disks`
 a| 
目标集群节点未检测到一个或多个 7- 模式备用磁盘。



 a| 
`ignore-missing-degraded-aggr-disks`
 a| 
无法从目标集群节点上的任何 7- 模式 RAID-DP RAID 组检测到最多两个磁盘，也无法从任何 7- 模式 RAID-4 RAID 组检测到一个磁盘。

继续过渡会使此类聚合在过渡后降级。

|===


== 导入操作：可忽略的错误类别

如果在导入操作期间向无副本过渡项目添加可忽略的错误类别，则 Data ONTAP 除了将阻止错误更改为警告之外，还会对聚合和卷执行一些更正操作。

|===
| 类别 | 显示错误时 | 确认错误并执行导入操作时的更正操作 重新运行 


 a| 
`ignore-aggregate-wing-32bit-snapshot-for-import`
 a| 
在 7- 模式聚合中检测到 32 位 Snapshot 副本。
 a| 
此项目中的所有 7- 模式聚合都会删除 32 位 Snapshot 副本。



 a| 
`transition-dirty-aggregate-during 导入`
 a| 
正在过渡的某个聚合未在 7- 模式存储系统上完全关闭。
 a| 
未完全关闭的所有 7- 模式聚合都会进行过渡。这可能会导致过渡后数据丢失。



 a| 
`ignore-aggregate-not-being -online for-import`
 a| 
当 7- 模式存储系统暂停时，聚合未联机。
 a| 
所有脱机聚合都会联机。



 a| 
`ignore-volume-wing-32bit-snapshot-for-import`
 a| 
在 7- 模式卷中检测到 32 位 Snapshot 副本。
 a| 
将从此项目中的所有 7- 模式卷中删除 32 位 Snapshot 副本。



 a| 
`ignore-volume-with -diry-file-system-for-import`
 a| 
在 7- 模式存储系统上，一个正在过渡的卷未完全关闭。
 a| 
未完全关闭的所有 7- 模式卷都会过渡。这可能会导致过渡后数据丢失。



 a| 
`transition-offline-volume-during 导入`
 a| 
当 7- 模式存储系统暂停时，卷未联机。
 a| 
所有脱机卷都会联机。



 a| 
`transition-restricted-volume-during 导入`
 a| 
当 7- 模式存储系统暂停时，卷处于受限状态。
 a| 
所有受限卷都会联机。

|===


== 提交操作：可忽略的错误类别

如果在提交操作期间向无副本过渡项目添加可忽略的错误类别，则 ONTAP 除了将阻止错误更改为警告之外，还会对聚合和卷执行一些更正操作。

|===
| 类别 | 显示错误时 | 确认错误并执行提交操作时的更正操作 重新运行 


 a| 
`ignore-commit-offline-aggregates`
 a| 
某些过渡后的聚合已脱机。
 a| 
所有脱机聚合都会联机。

|===