---
permalink: copy-free/task_exporting_7_mode_system_and_hardware_information.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, exporte, storage, configurations, halt 
summary: 过渡的转换窗口从导出阶段开始。在此阶段，该工具会从 7- 模式系统收集系统信息，磁盘架详细信息和存储配置，然后暂停 7- 模式存储系统。 
---
= 导出存储配置并暂停 7- 模式系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
过渡的转换窗口从导出阶段开始。在此阶段，该工具会从 7- 模式系统收集系统信息，磁盘架详细信息和存储配置，然后暂停 7- 模式存储系统。

* 必须在 7- 模式系统上为服务处理器（ SP ）或远程 LAN 模块（ RLM ）配置 IPv4 地址。
* 所有客户端都必须与 7- 模式系统断开连接（方法是卸载 NFS 导出，断开 CIFS 共享并关闭 SAN 主机），但适用的 NAS 和 SAN 服务必须在 7- 模式系统上运行。
+

IMPORTANT: 您不能停止任何协议服务，因为从 7- 模式存储系统收集协议配置时需要这些服务。

* 在此操作期间写入 7- 模式卷的所有数据都将丢失。
* 在此操作期间，您不能对 7- 模式系统执行任何管理操作。
* 该工具会在导出阶段执行以下操作：
+
** 收集所有卷和存储配置
** 为每个过渡聚合创建一个 Snapshot 副本
+
如果您决定在过渡的任何阶段还原到 7- 模式，该工具将使用这些 Snapshot 副本执行还原操作。

** 在维护模式下启动 7- 模式控制器
** 从 7- 模式控制器中删除磁盘所有权
** 在目标集群节点上禁用磁盘自动分配




.步骤
. 单击 * 导出并暂停 * 。
+
此时将显示一条消息，其中列出了此操作的重要注意事项。

. 单击 * 确认客户端访问已断开连接 * 复选框。
. 单击 * 是 * 继续执行导出并暂停操作。
+
此时将显示操作结果。

. 等待操作完成，然后执行以下步骤以保存操作结果并收集工具日志：
+
.. 单击 * 另存为 CSV* 以将操作结果保存在文件中。
.. 单击 * 收集工具日志 * 为所有过渡日志文件创建备份。
+
最好在每次过渡操作后保存日志文件。

.. 单击 * 关闭 * 以关闭操作结果窗口。


+
如果操作需要很长时间才能完成，您可以单击 * 在后台运行 * 退出操作结果窗口。当操作在后台运行时，您不应编辑项目或执行任何其他任务。然后，您可以从操作历史记录选项卡查看操作结果。


