---
permalink: copy-free/task_performing_a_transition_rollback.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, roll, back, project 
summary: 如果要在提交过渡后的聚合之前无副本过渡的任何阶段还原到 7- 模式，则可以回滚过渡。回滚是一项手动操作。您可以使用 7- 模式过渡工具生成回滚时必须执行的手动步骤。 
---
= 回滚无副本过渡项目
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要在提交过渡后的聚合之前无副本过渡的任何阶段还原到 7- 模式，则可以回滚过渡。回滚是一项手动操作。您可以使用 7- 模式过渡工具生成回滚时必须执行的手动步骤。

* 您必须确保集群上未运行任何卷或聚合过渡操作。
+
您可以使用 `job show -jobtype transition` 命令。

* 不能提交任何 7- 模式聚合。
+

NOTE: 即使提交了一个 7- 模式聚合，也无法执行回滚。

* 目标集群节点不能处于接管模式。


.步骤
. 单击 * 回滚预检 * 以验证项目是否符合回滚条件。
+
如果预检报告了问题，则必须手动修复这些问题并重新运行预检操作。例如，如果您在预生产测试期间创建了任何新卷或 LUN ，则必须手动删除它们。

. 单击 * 生成回滚步骤 * 以生成成功回滚必须执行的手动步骤列表。
. 单击 * 另存为 CSV* 以将手动步骤保存在文件中。
+
您可以从文件复制回滚命令并运行这些命令。

. 根据决定回滚的过渡阶段，执行所需的手动步骤：
+
** * 导入或预生产测试阶段 *
+
... 在集群上运行回滚命令，然后单击 * 确认 * 。
... 将 7- 模式磁盘架连接到 7- 模式控制器，手动验证布线，然后单击 * 确认 * 。
... 在 7- 模式控制器上运行回滚命令，然后单击 * 确认 * 。
... 从操作历史记录选项卡查看应用于 SVM 的配置。
... 从 SVM 中手动删除此工具应用的所有配置。


** * 布线阶段 *
+
... 将 7- 模式磁盘架连接到 7- 模式控制器，手动验证布线，然后单击 * 确认 * 。
+
您必须确保 7- 模式布线与项目开始时的布线方式一致。

+

NOTE: 您应使用 Config Advisor 验证布线。

... 在 7- 模式控制器上运行回滚命令，然后单击 * 确认 * 。
... 从 SVM 中手动删除此工具应用的所有配置。
+
您可以从操作历史记录选项卡查看应用于 SVM 的配置。



** * 导出阶段 *
+
... 在 7- 模式控制器上运行回滚命令，然后单击 * 确认 * 。
... 从 SVM 中手动删除此工具应用的所有配置。
+
您可以从操作历史记录选项卡查看应用于 SVM 的配置。



** * SVM 配置阶段 *
+
从 SVM 中手动删除此工具应用的所有配置。

+
您可以从操作历史记录选项卡查看应用于 SVM 的配置。



+
xref:task_running_manual_steps_for_rolling_back_transition.adoc[回滚过渡的手动步骤]

. 完成所有手动步骤后，单击 7- 模式过渡工具中的 * 验证 7- 模式 * 以验证 7- 模式控制器是否已准备好提供数据。

