---
permalink: copy-free/task_generating_fc_zone_plan.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, fc, zone, plan 
summary: 对于 FC 交换机，您必须在过渡评估报告中生成 FC 分区计划，以配置分区，以便在迁移后对启动程序主机和目标进行分组。 
---
= 生成 FC 分区计划
:icons: font
:imagesdir: ../media/


[role="lead"]
对于 FC 交换机，您必须在过渡评估报告中生成 FC 分区计划，以配置分区，以便在迁移后对启动程序主机和目标进行分组。

* 7- 模式系统，主机和集群必须连接到同一交换机。
+
xref:concept_supported_configurations_for_generating_an_fc_zone_plan.adoc[支持用于生成 FC 分区计划的配置]

* 您必须已在集群上创建所需的目标 SVM 和 FC LIF 。
* 在目标 SVM 上创建的 FC LIF 将具有 WWPN ，这与 7- 模式 WWPN 不同。因此，请在过渡 FCP 的 SAN 时执行 FC 分区。


.步骤
. 在收集和评估部分中，单击 * 添加系统 * 。
. 在添加系统窗口中，执行以下操作之一：
+
** 添加单个系统：
+
... 输入系统的 FQDN 或 IP 地址。
... 输入指定系统的用户名和密码。
... 选择系统类型：
+
**** Data ONTAP 存储系统
**** 主机： Microsoft Windows ， Red Hat Linux Enterprise 和 VMware ESXi
**** FC 交换机： Cisco 和 Brocade




** 单击 * 浏览 * 添加多个系统，然后选择包含多个系统凭据的文本文件。


. 单击 * 添加 * 。
+
如果系统的评估状态为 Ready ，则可以对该系统执行过渡评估。

. 生成包含 FC 分区计划的过渡评估报告：
+
.. 选择用于过渡评估的系统，包括所需的 FC 交换机。
.. 单击 * 创建过渡评估报告 * 。
.. 在 Pair systems and start FC zone Planner 对话框中，选择 7- 模式系统（单控制器或 HA 对），连接到集群的交换机以及集群中的 SVM 。
+
如果您计划通过重新托管过渡后的卷将 FC LUN 整合到一个 SVM ，请选择 7- 模式 HA 对和目标 SVM 。

+

NOTE: 最佳做法是将 FC LUN 整合到一个 SVM 中，以保留 7- 模式单系统映像（ SSI ）配置。

+
如果您不打算整合 FC LUN ，则必须为每个 7- 模式控制器以及相应的目标 SVM 生成 FC 分区计划。

.. 单击 * 配对系统的 FC 分区 * 。
.. 在创建过渡评估报告对话框中，选择目标集群的 Data ONTAP 版本。
.. 为报告的文件名指定前缀。
.. 单击 * 生成报告 * 。




FC 分区计划将以 ` .zip` 文件的形式生成。该计划包含在 7- 模式系统上根据 igroup 配置创建的分区。每个分区都包含一个启动程序 WWPN 和多个 SVM 目标 WWPN 。

您必须使用 FC 分区计划配置分区，以便对启动程序主机和目标进行分组，以便从集群提供数据访问。
