---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_staggered_way.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, ha, pairs, snapmirror, relationship, staggered, configuration 
summary: 您可以先过渡二级 HA 对，在 7- 模式主卷和 ONTAP 二级卷之间设置交错的 SnapMirror 关系，然后再过渡主 HA 对。 
---
= 交错过渡 SnapMirror 关系中的 HA 对 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以先过渡二级 HA 对，在 7- 模式主卷和 ONTAP 二级卷之间设置交错的 SnapMirror 关系，然后再过渡主 HA 对。

您必须已准备好源和目标集群，以便过渡 SnapMirror 关系。

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[准备集群以过渡卷 SnapMirror 关系]

.步骤
. 在 7- 模式过渡工具中，对包含 7- 模式卷 SnapMirror 关系的二级卷的 HA 对执行无副本过渡。
+
过渡包含二级卷的 7- 模式 HA 对之前，无需手动干预 7- 模式 SnapMirror 关系。这样可以确保 7- 模式二级卷作为只读卷过渡到 ONTAP 。

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[使用无副本过渡过渡过渡过渡过渡 7- 模式聚合]

. 在二级 HA 对的预提交测试阶段，在 7- 模式主卷和 ONTAP 二级卷之间创建灾难恢复关系：
+
.. 在二级目标集群中，使用 `vserver peer transition create` 命令在 7- 模式主卷和 ONTAP 二级卷之间创建 SVM 对等关系。
.. 使用 `job schedule cron create` 命令创建与为 7- 模式 SnapMirror 关系配置的计划匹配的作业计划。
.. 使用 `snapmirror create` 命令在 7- 模式主卷和 ONTAP 二级卷之间创建 TDP 类型的 SnapMirror 关系。
.. 使用 `snapmirror resync` 命令重新同步 ONTAP 二级卷。
+
要成功重新同步， 7- 模式主卷和 ONTAP 二级卷之间必须存在一个通用的 7- 模式 Snapshot 副本。



. 对过渡后的聚合和卷执行所需的测试。
. 在 7- 模式过渡工具中，提交二级 HA 对的项目过渡。
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[提交无副本过渡项目]

. 对包含 7- 模式卷 SnapMirror 关系中的主卷的 HA 对执行无副本过渡。
+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[使用无副本过渡过渡过渡过渡过渡 7- 模式聚合]

. 在主 HA 对的预提交测试阶段，在过渡后的二级卷和主卷之间创建 SnapMirror 关系。
+
.. 从目标集群中，在包含过渡后的主卷和二级卷的 SVM 之间创建集群间 SVM 对等关系。
+
https://["系统管理"]

.. 使用 `snapmirror delete` 命令删除 TDP SnapMirror 7- 模式主卷与 ONTAP 二级卷之间的关系 在步骤中创建的卷 <<SUBSTEP_D528769DF8EC49058D1958565914CF47,#substed_d528769DF8EC49058D1958565914CF47>>。
.. 删除在步骤中创建的 cron 作业计划 <<SUBSTEP_EB470706425C45759EAAE8F0A87BA547,#substed_EB470706425C45759EAAE8F0A87BA547>>： + ` * 作业计划 cron delete*`
.. 在过渡后的主卷和二级卷之间创建卷 SnapMirror 关系。
+
https://["卷灾难恢复快速准备"]

.. 在目标卷上，重新同步 SnapMirror 关系的源卷和目标卷： + ` * snapmirror resynchron*`
+

IMPORTANT: 源卷和目标卷之间必须至少存在一个通用 Snapshot 副本。

+
* 故障排除： * 如果通用 Snapshot 副本是在 8.1 之前的 Data ONTAP 版本中创建的，则 SnapMirror 重新同步将失败。您可以在高级权限级别将 ` -fs-version` 参数与 `volume snapshot show` 命令结合使用，以查看创建 Snapshot 副本的版本。如果发生此问题描述，请中断 SnapMirror 关系，然后执行重新同步。

.. 监控 SnapMirror 数据传输的状态： + ` * snapmirror show*`
+

IMPORTANT: 重新同步成功完成之前，不得对源卷和目标卷执行任何操作，例如卷移动或 SnapMirror 中断。确保重新同步不会中止并成功完成；否则，卷可能会处于不一致状态。



. 提交主项目的过渡。
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[提交无副本过渡项目]



* 相关信息 *

http://["使用 SnapMirror 进行 7- 模式数据过渡"]

http://["ONTAP 9 命令"]
