---
permalink: copy-free/task_importing_7_mode_data_to_clustered_ontap.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, import, data 
summary: 验证布线并解决任何问题后，您可以运行导入操作。在此阶段，磁盘所有权将分配给映射的集群节点，并将 7- 模式聚合，卷和 LUN 转换为 ONTAP 格式。此外，还会应用所有卷级别和 LUN 级别配置。 
---
= 将 7- 模式数据导入 ONTAP
:icons: font
:imagesdir: ../media/


[role="lead"]
验证布线并解决任何问题后，您可以运行导入操作。在此阶段，磁盘所有权将分配给映射的集群节点，并将 7- 模式聚合，卷和 LUN 转换为 ONTAP 格式。此外，还会应用所有卷级别和 LUN 级别配置。

此工具在此阶段会执行以下操作：

* 7- 模式磁盘将分配给映射的目标集群节点。
* 所有 7- 模式聚合，卷和 LUN 都会转换为 ONTAP 格式。
* 选择进行过渡的 7- 模式 IP 地址将在管理启动状态下在 SVM 上进行配置。
* 将应用以下配置：
+
** NFS 导出规则
** CIFS 共享
** CIFS ACL 配置
** CIFS 主目录配置
** CIFS 符号链接
** 配额配置
** Snapshot 副本计划
** LUN 映射和 igroup




.步骤
. 单击 * 导入 * 。
+
* 故障排除： * 如果聚合中缺少磁盘，则聚合将降级，导入操作将失败。如果缺少的磁盘数量在允许的限制范围内，则可以通过在 7- 模式过渡工具命令行界面中运行以下命令，在已降级的聚合中继续过渡：

+
` * 过渡 CFT 聚合 degraded-transition -p _project-name_ -n _7-mode-host-name_ -a _7-mode-aggregate-name_ -I acknowledge *`

+
然后，您可以重新运行布线验证操作并继续过渡。您必须确保目标集群节点中有足够的备用磁盘，以便在过渡聚合后重建这些 RAID 组。

+
此时将显示一条警告消息，其中列出了此操作的重要注意事项。

. 单击 * 是 * 继续。
+
此时将显示操作结果。

. 等待操作完成，然后执行以下操作：
+
.. 单击 * 另存为 CSV* 以将操作结果保存在文件中。
.. 单击 * 收集工具日志 * 为所有过渡日志文件创建备份。
+
最好在每次过渡操作后保存日志文件。

.. 单击 * 关闭 * 以关闭操作结果窗口。


+
如果操作需要很长时间才能完成，您可以单击 * 在后台运行 * 退出操作结果窗口。当操作在后台运行时，您不应编辑项目或执行任何其他任务。然后，您可以从操作历史记录选项卡查看操作结果。


