---
permalink: copy-free/task_applying_svm_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, apply, svm, configurations 
summary: 您必须在 SVM 配置阶段之前手动应用某些配置。然后，您可以使用工具将在 7- 模式控制器（ /etc 目录中的文件）或 vFiler 单元级别定义的所有配置应用于映射的 SVM 。 
---
= 正在应用 SVM 配置
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须在 SVM 配置阶段之前手动应用某些配置。然后，您可以使用工具将在 7- 模式控制器（ ` /etc` 目录中的文件）或 vFiler 单元级别定义的所有配置应用于映射的 SVM 。

如果您不想将所有配置过渡到目标 SVM ，则必须为要在 SVM 上排除的配置设置属性。

xref:task_customizing_configurations_for_transition.adoc[自定义 7- 模式配置的过渡]

* 在 SVM 配置阶段， NFS 导出， CIFS 共享和 LUN 映射等配置不会应用于 SVM 。
* 在 SVM 配置阶段，此工具会在 SVM 上应用以下配置：
+
** * 名称服务 *
+
*** DNS 配置
*** LDAP 配置
*** NIS 配置
*** 名称服务开关配置
*** 主机配置
*** UNIX 用户和组
*** 网络组配置


** * 网络连接 *
+
*** 选择进行过渡的现有 7- 模式 IP 地址将在管理关闭状态下创建。
+
在导入阶段，这些 IP 地址会配置为管理启动状态。

*** 在管理启动状态下创建新的 IP 地址。


** * NFS *
+
NFS 选项

** * CIFS*
+
*** CIFS 首选 DC 配置
*** 用户映射配置
*** Widelink 配置
*** CIFS 选项
*** 审核配置


** * SAN *
+
FC 和 iSCSI 服务

+
[IMPORTANT]
====
成功完成此操作后，您将无法重新运行此操作。

因此，如果在此操作之后对 7- 模式控制器级别的配置进行任何更改，则必须在导出阶段之前手动将配置过渡到目标 SVM 。例如，如果在此操作后将新的 vFiler 单元添加到 7- 模式控制器并将其映射到 SVM ，则必须手动将该 vFiler 单元的配置过渡到映射的 SVM 。另一个示例是，如果在 SVM 配置阶段之后在 7- 模式控制器上添加了一些 UNIX 用户，则必须在映射的 SVM 上手动创建这些 UNIX 用户。

====




.步骤
. 单击 * 应用 SVM 配置 * 将 7- 模式配置应用于目标 SVM 。
+
此时将显示一条确认消息，其中列出了此操作的重要注意事项。

. 单击 * 是 * 继续。
. 操作完成后，请执行以下步骤：
+
.. 单击 * 另存为 CSV* 以将操作结果保存在文件中。
.. 单击 * 收集项目日志 * ，为所有过渡日志文件创建备份。
+
最好在每次过渡操作后保存日志文件。

.. 单击 * 关闭 * 以关闭操作结果窗口。


+
如果操作需要很长时间才能完成，您可以单击 * 在后台运行 * 退出操作结果窗口。当操作在后台运行时，您不应编辑项目或执行任何其他任务。然后，您可以从操作历史记录选项卡查看操作结果。

. 验证并测试手动应用于目标 SVM 的配置，并进行所需的更改。
. 手动验证与外部名称服务器的连接。

