---
permalink: copy-free/task_gathering_cabling_information_for_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, gather, cabling, information 
summary: 在开始无副本过渡之前，您必须收集有关 7- 模式控制器的适配器，端口，磁盘架和存储连接的信息，然后规划如何将 7- 模式磁盘架连接到目标集群节点。 
---
= 收集用于过渡的布线信息
:icons: font
:imagesdir: ../media/


[role="lead"]
在开始无副本过渡之前，您必须收集有关 7- 模式控制器的适配器，端口，磁盘架和存储连接的信息，然后规划如何将 7- 模式磁盘架连接到目标集群节点。

您必须已打印无副本过渡布线工作表。

xref:reference_copy_free_transition_cabling_worksheet.adoc[无副本过渡布线工作表]

. 使用 Config Advisor 对 7- 模式存储和布线执行运行状况检查并收集布线数据。
+
您应使用 Data ONTAP 7 和 8 （ 7- 模式）` 执行配置文件中的 `7- 模式安装检查` 选项。

. 使用以下命令收集有关每个 7- 模式控制器的所需信息：
+
` * sysconfig _slot_number_*`

+
您可以使用此命令的输出来确定用于磁盘架连接的端口。

+
[listing]
----
host1> sysconfig 3
        slot 3: SAS Host Adapter 3a
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3b
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3c
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3d
                24 Disks:            13440.0GB
                1 shelf with IOM3
----
. 在集群中，对每个节点运行以下 nodeshell 命令：
+
` * 系统节点 run -node _node_name_ -command sysconfig -A*`

+
您可以使用此命令的输出来获取有关可用端口和扩展卡插槽的信息。

. 在目标集群节点上，规划用于连接 7- 模式磁盘架的端口：
+
.. 查看可用（开放）端口。
.. 查看扩展卡插槽。
.. 规划扩展卡配置。
+
如果目标平台和 ONTAP 版本也支持扩展卡，您可以计划将其从 7- 模式系统中移动。如果需要，您还可以规划 PAM 卡。

+
https://hwu.netapp.com["NetApp Hardware Universe"]

.. 规划用于磁盘架布线的目标端口。
+
选择目标端口取决于以下某些因素：

+
*** 单独或现有磁盘架堆栈
*** 端口可用性
*** SAS 或 FC 连接
*** 板载端口或扩展卡的可用性




. 转至数据中心，在布线工作表中以物理方式记录 7- 模式控制器和目标集群节点上的端口连接：
+
.. 在布线工作表中记录 7- 模式控制器上使用的端口。
.. 在布线工作表中记录目标集群节点上的已用端口。
.. 按照步骤中的计划，记录用于连接 7- 模式磁盘架的目标端口 <<STEP_D0CFE719A0384F7FA5D9E73C8EA6C2E7,#sted_D0CFE719A0384F7FA5D9E73C8EA6C2E7>>。
.. 确保使用合适的缆线连接磁盘架。
+
您应根据新的磁盘架堆栈位置确定布线的任何问题。

.. 根据梯形机架或数据中心的要求，规划较长的缆线长度。
.. 为 7- 模式控制器上的每个磁盘架堆栈和缆线贴上标签。
+
最佳做法是，为 7- 模式磁盘架堆栈贴上标签，以防您要回滚过渡并将磁盘架重新连接到 7- 模式控制器。





* 相关信息 *

https://library.netapp.com/ecm/ecm_download_file/ECMP1119629["《适用于 DS4243 ， DS2246 ， DS4486 和 DS4246 的 SAS 磁盘架安装和服务指南》"]

https://library.netapp.com/ecm/ecm_download_file/ECMM1280273["《 DiskShelf14mk2 AT 硬件服务指南》"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1112854["《 DS14mk2 FC 和 DS14mk4 FC 硬件服务指南》"]
