---
permalink: snapmirror/task_transitioning_a_stand_alone_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, stand, alone, volume, snapmirror 
summary: 过渡独立卷涉及创建 SnapMirror 关系，执行基线传输，执行增量更新，监控数据复制操作，中断 SnapMirror 关系以及将客户端访问从 7- 模式卷移动到集群模式 Data ONTAP 卷。 
---
= 过渡独立卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
过渡独立卷涉及创建 SnapMirror 关系，执行基线传输，执行增量更新，监控数据复制操作，中断 SnapMirror 关系以及将客户端访问从 7- 模式卷移动到集群模式 Data ONTAP 卷。

* 必须已设置集群和 SVM 。
* 您必须已查看有关过渡准备的信息。
+
xref:task_preparing_for_transition.adoc[为过渡做准备]



NetApp建议您配置目标ONTAP 卷以匹配7-模式源卷的属性。要匹配的某些属性包括：

* Volume Size：ONTAP 卷必须至少为7-模式卷的大小。
* Language：ONTAP 卷设置应与7-模式卷的设置匹配。


7-模式过渡工具会自动为ONTAP 卷配置与7-模式卷匹配的属性。

.步骤
. 将数据从 7- 模式卷复制到集群模式 Data ONTAP 卷：
+
.. 如果要为 7- 模式系统和 SVM 之间的 SnapMirror 关系配置 TCP 窗口大小，请使用 `window-size-for-TDP mirror` 选项创建类型为 `async-mirror` 的 SnapMirror 策略。
+
然后，必须将此策略应用于 7- 模式系统与 SVM 之间的 TDP SnapMirror 关系。

+
您可以将 TCP 窗口大小配置为 256 KB 到 7 MB ，以提高 SnapMirror 传输吞吐量，从而加快过渡副本操作的完成速度。TCP 窗口大小的默认值为 2 MB 。

+
[listing]
----
cluster1::> snapmirror policy create -vserver vs1 –policy tdp_policy -window-size-for-tdp-mirror 5MB -type async-mirror
----
.. 使用关系类型为 TDP 的 `snapmirror create` 命令在 7- 模式系统和 SVM 之间创建 SnapMirror 关系。
+
如果您已创建 SnapMirror 策略来配置 TCP 窗口大小，则必须将此策略应用于此 SnapMirror 关系。

+
[listing]
----
cluster1::> snapmirror create -source-path system7mode:dataVol20 -destination-path vs1:dst_vol -type TDP -policy tdp_policy
Operation succeeded: snapmirror create the relationship with destination vs1:dst_vol.
----
.. 使用 `snapmirror initialize` 命令启动基线传输。
+
[listing]
----
cluster1::> snapmirror initialize -destination-path vs1:dst_vol
Operation is queued: snapmirror initialize of destination vs1:dst_vol.
----
.. 使用 `snapmirror show` 命令监控状态。
+
[listing]
----
cluster1::>snapmirror show -destination-path vs1:dst_vol

                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           **Mirror State: Snapmirrored**
                    Relationship Status: Idle
                File Restore File Count: -
                 File Restore File List: -
                      Transfer Snapshot: -
                      Snapshot Progress: -
                         Total Progress: -
              Network Compression Ratio: -
                    Snapshot Checkpoint: -
                        Newest Snapshot: vs1(4080431166)_dst_vol.1
              Newest Snapshot Timestamp: 10/16 02:49:03
                      Exported Snapshot: vs1(4080431166)_dst_vol.1
            Exported Snapshot Timestamp: 10/16 02:49:03
                                Healthy: true
                       Unhealthy Reason: -
               Constituent Relationship: false
                Destination Volume Node: cluster1-01
                        Relationship ID: 97b205a1-54ff-11e4-9f30-005056a68289
                   Current Operation ID: -
                          Transfer Type: -
                         Transfer Error: -
                       Current Throttle: -
              Current Transfer Priority: -
                     Last Transfer Type: initialize
                    Last Transfer Error: -
                     Last Transfer Size: 152KB
Last Transfer Network Compression Ratio: 1:1
                 Last Transfer Duration: 0:0:6
                     Last Transfer From: system7mode:dataVol20
            Last Transfer End Timestamp: 10/16 02:43:53
                  Progress Last Updated: -
                Relationship Capability: 8.2 and above
                               Lag Time: -
           Number of Successful Updates: 0
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 155648
         Total Transfer Time in Seconds: 6
----
.. 根据您是要手动更新集群模式 Data ONTAP 卷还是通过设置 SnapMirror 计划来更新此卷，请执行相应的操作：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
手动更新传输
 a| 
... 使用 `snapmirror update` 命令。
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
----
... 使用 `snapmirror show` 命令监控数据复制状态。
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... 转至步骤 3 。




 a| 
执行计划的更新传输
 a| 
... 使用 `job schedule cron create` 命令为更新传输创建计划。
+
[listing]
----
cluster1::> job schedule cron create -name 15_minute_sched -minute 15
----
... 使用 `snapmirror modify` 命令将计划应用于 SnapMirror 关系。
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule 15_minute_sched
----
... 使用 `snapmirror show` 命令监控数据复制状态。
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. 如果您有增量传输计划，请在准备好执行转换时执行以下步骤：
+
.. 使用 `snapmirror quiesce` 命令禁用所有未来的更新传输。
+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs1:dst_vol
----
.. 使用 `snapmirror modify` 命令删除 SnapMirror 计划。
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule ""
----
.. 如果您先前暂停了 SnapMirror 传输，请使用 `snapmirror resume` 命令启用 SnapMirror 传输。
+
[listing]
----
cluster1::> snapmirror resume -destination-path vs1:dst_vol
----


. 等待 7- 模式卷和集群模式 Data ONTAP 卷之间正在进行的任何传输完成，然后断开 7- 模式卷的客户端访问以启动转换。
. 使用 `snapmirror update` 命令对集群模式 Data ONTAP 卷执行最终数据更新。
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
Operation is queued: snapmirror update of destination vs1:dst_vol.
----
. 使用 `snapmirror show` 命令验证上次传输是否成功。
. 使用 `snapmirror break` 命令中断 7- 模式卷与集群模式 Data ONTAP 卷之间的 SnapMirror 关系。
+
[listing]
----
cluster1::> snapmirror break -destination-path vs1:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. 如果您的卷配置了 LUN ，请在高级权限级别使用 `lun transition 7-mode show` 命令验证 LUN 是否已过渡。
+
您也可以在集群模式 Data ONTAP 卷上使用 `lun show` 命令查看已成功过渡的所有 LUN 。

. 使用 `snapmirror delete` 命令删除 7- 模式卷与集群模式 Data ONTAP 卷之间的 SnapMirror 关系。
+
[listing]
----
cluster1::> snapmirror delete -destination-path vs1:dst_vol
----
. 使用 `snapmirror release` 命令从 7- 模式系统中删除 SnapMirror 关系信息。
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----


将 7- 模式系统中所有必需卷过渡到 SVM 后，必须删除 7- 模式系统与 SVM 之间的 SVM 对等关系。

* 相关信息 *

xref:task_resuming_a_failed_snapmirror_transfer_transition.adoc[恢复失败的 SnapMirror 基线传输]

xref:task_recovering_from_a_failed_lun_transition.adoc[从失败的 LUN 过渡中恢复]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[为 SnapMirror 关系配置 TCP 窗口大小]
